//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildCouchObjects {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CouchDocs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CouchDocs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BuildCouchObjects.CouchDocs", typeof(CouchDocs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;clientId&quot;: 1000,
        ///  &quot;machineId&quot;: &quot;1416394498660266215&quot;,
        ///  &quot;ipAddress&quot;: &quot;86.170.41.197&quot;,
        ///  &quot;userAgent&quot;: &quot;Mozilla/5.0 (Linux; U; Android 4.4.2; en-us; KFSOWI Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Silk/3.37 like Chrome/34.0.1847.137 Safari/537.36&quot;,
        ///  &quot;deviceFingerPrint&quot;: &quot;e88e99a271165ab77eb5958aca130019&quot;,
        ///  &quot;status&quot;: &quot;Active&quot;,
        ///  &quot;customer&quot;: {
        ///    &quot;firstName&quot;: &quot;&quot;,
        ///    &quot;lastName&quot;: &quot;&quot;,
        ///    &quot;salutation&quot;: &quot;&quot;,
        ///    &quot;email&quot;: &quot;ken.tuck@salecycle.com&quot;,
        ///    &quot;mobile&quot;: &quot;&quot;,
        ///    &quot;landline&quot;: &quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SessionSeed {
            get {
                return ResourceManager.GetString("SessionSeed", resourceCulture);
            }
        }
    }
}
